include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/generated/**
  language:
    strict-casts: false
    strict-raw-types: false

linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    prefer_if_elements_to_conditional_expressions: false
    cascade_invocations: false
    prefer_const_constructors: false
    omit_local_variable_types: false
    unnecessary_lambdas: false
    discarded_futures: false
    avoid_redundant_argument_values: false
    prefer_int_literals: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    always_use_package_imports: false
    unreachable_from_main: false
    unawaited_futures: false
    simplify_variable_pattern: false
    leading_newlines_in_multiline_strings: false
    use_colored_box: false
    avoid_escaping_inner_quotes: false